config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :vehicles, except: [:edit, :update] do
    resources :pages, only: [:new, :create]
    resources :bookings, only: :create
    resources :vehicles, :yachts
  end
  resources :vehicles, only: [:destroy, :index, :yachts]
  resources :bookings, only: [:destroy, :index, :show]
  resources :beds, only: [:index, :new, :show]

  get "/mylistings", to: "vehicles#mylistings"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vehicles, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  geocoded_by :address
  has_many :bookings, dependent: :destroy
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_one_attached :image
  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: {
    in: %w(Car Limosuine Aircraft Yacht),
    message: 'must be either Car Limosuine Aircraft or Yacht'
  }

  include PgSearch::Model

  pg_search_scope :global_search,
  against: [ :name, :description ],
  associated_against: {
    director: [ :name, :description ]
  },
  using: {
    tsearch: { prefix: true }
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController


  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @booking = Booking.new(booking_params)
    @booking.vehicle = @vehicle
    @booking.user = current_user
    # # @booking.status = "Pending host validation"
    # if @booking.checkout_on && @booking.checkin_on
    #   @booking.value = (@booking.checkout_on - @booking.checkin_on).to_f * @booking.vehicle.price.to_f
    # else
    #   @booking.value = 0
    # end
    if @booking.save
      redirect_to booking_path(@booking)
    else
      redirect_to vehicle_path(@vehicle)
    end
  end

  def index
    @bookings = Booking.where(user_id: current_user.id)
    # set_booking
    # @vehicle = @booking.vehicle
    # @review = Review.new
  end

  def show
    set_booking
    @vehicle = @booking.vehicle
  end

  def update
    set_booking
    # @booking.status = "Pending host validation"
    @booking.save!
    redirect_to booking_path(@booking)
  end

  def destroy
    set_booking
    @booking.destroy
    redirect_to root_path, status: :see_other
  end


  private

  def booking_params
    params.require(:booking).permit(:date, :hours)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
before_action :set_list, only: [:show, :destroy]

def index
  if params[:query].present?
    sql_query = "name ILIKE :query OR description ILIKE :query"
    @vehicles = Vehicle.where(sql_query, query: "%#{params[:query]}%")
  else
    @vehicles = Vehicle.all
    @markers = @vehicles.geocoded.map do |vehicle|
      if vehicle.category == "Yacht"
        pic = "8150.png"
      elsif vehicle.category == "Car"
        pic = "car.png"
      end

      {
        category: vehicle.category,
        lat: vehicle.latitude,
        lng: vehicle.longitude,
        info_window: render_to_string(partial: "info_window", locals: {vehicle: vehicle}),
        image_url: helpers.asset_url(pic)
      }
    end
  end
end


  def show
    @booking = Booking.new
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user
    if @vehicle.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @vehicle.destroy
    redirect_to vehicles_path, status: :see_other
  end

  def mylistings
    @vehicles = Vehicle.where(user: current_user)
  end
  private

  def set_list
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    #TODO
		params.require(:vehicle).permit(:name, :description, :category, :price, :image, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="text-center padded">
<h1>All your reservations</h1>
</div>
<div class="wrapper-dashboard">
    <% @bookings.each do |booking| %>
          <aside class="profile-card">
            <header>
              <a target="_blank" href="<%=booking.id%>">
                <%= cl_image_tag booking.vehicle.image.key %>
              </a>
                <br>
                <br>
              <h4>
                    <strong><%= booking.vehicle.name %></strong></p>
                    </h4>
            </header>
              <div class = "profile-bio" >
              <h4>Date: <%= booking.date[13] %> </h4>
               <h4>   Month:  <%= booking.date[19..20] %> </h4>
                <h4>  Year: <%= booking.date[4..7] %> </h4>
                <h4> Hours: <%= booking.hours %></h4>
                 <%=  link_to "DELETE", booking_path(booking.id), class: "btn button-24", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>

              </div>
        </aside>
    <% end %>
</div>

app/views/bookings/show.html.erb
<div class="map" style="background-image: url('<%= @vehicle.image %>')"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="vehicle-show-card">
        <h1>Vehicle: <%= @booking.vehicle.name %></h1>
<%= cl_image_tag @booking.vehicle.image.key %>
      </div>
      <div class="vehicle-show-card">
              <h3>Details:</h3>
        <h3>Email: <%= @booking.user.email %></h3>
        <br>
        <h3>Date: <%= @booking.date[13] %> / <%= @booking.date[19..20] %> / <%= @booking.date[4..7] %> </h3>
     </div>
    </div>

    <div class="col-4">
      <div class="vehicle-show-card">
          <div class="input-group">

      <div class="vehicle-show-card">
        <div class="flex">

          <br>
                  <h3>Hours: <%= @booking.hours %></h3>
            <br>
            <br>
</button>
    <button> <%=  link_to "DELETE", booking_path, class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %> </button>
    </div>
  </div>

          <div class="flex">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>

    <title>HireWay</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-light">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">  <%= link_to "Home", root_path, class: 'nav-link' %></a></li>
                        <li class="nav-item">  <%= link_to "Rent a vehicle", vehicles_path, class: 'nav-link' %></a></li>
                        <li class="nav-item">  <%= link_to "List", new_vehicle_path, class: 'nav-link' %></a></li>
                        <li class="nav-item">  <%= link_to "Bookings", bookings_path, class: 'nav-link' %></a></li>

                    </ul>
                </div>
            </div>
                    <%= render "shared/navbar" %>
        </nav>
  <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/_cards.html.erb
<section class="Home__cards">
  <div class="container">
    <h2 class="Home__cards-heading">Recently Added Boats</h2>
    <div class="row">
      <% @boats.each do |boat| %>
        <div class="col-sm-6 col-md-4">
          <%= render 'shared/card', boat: boat %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <div class="container">
            <div class="text-center mt-5">
                <h1>HireWay</h1>
                <p class="lead">Find a luxury vehicle, near you</p>
          </section>
            </div>
        </div>
    </body>
</html>
        <div class="row gx-0">
                    <div class="col-lg-6">
                        <a class="portfolio-item" href="/vehicles">

                            <div class="caption">
                                <div class="caption-content">
                                    <div class="h2">Cars</div>
                                    <p class="mb-0" >Find a luxury car</p>
                                </div>
                            </div>
                            <img src="https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80" class="img-fluid" alt="Responsive image">
                        </a>
                    </div>
                    <div class="col-lg-6">
                        <a class="portfolio-item" href="/vehicles">
                            <div class="caption">
                                <div class="caption-content">
                                    <div class="h2">Boats</div>
                                    <p class="mb-0">Find a luxury boat</p>
                                </div>
                            </div>
                            <img src="https://images.unsplash.com/photo-1517988368819-88f4eacfef44?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" class="img-fluid" alt="Responsive image">
                        </a>
                    </div>
                    </div>
                    <br>
                    <br>
                    <h4><strong> HOW IT WORKS</strong> </h4>
                  <div class="box" >
    <div class="container">
      <div class="row">

          <div class="col" style="width: 18rem;">

          <div class="box-part text-center">

                        <i class="fa-solid fa-sailboat fa-3x" aria-hidden="true"></i>
                        <i class="fa-solid fa-car fa-3x" aria-hidden="true"></i>

            <div class="title">
                        <br>
                        <br>
              <h4>Rent</h4>
            </div>

            <div class="text">
              <span>Find a luxury vehicle near you and book it for rent!</span>
            </div>

           </div>
        </div>

         <div class="col" style="width: 18rem;">

          <div class="box-part text-center">

              <i class="fa-solid fa-face-laugh-beam fa-3x" aria-hidden="true"></i>

            <div class="title">
            <br>
            <br>
              <h4>Enjoy your ride!</h4>
            </div>

            <div class="text">
              <span>Take your ride and take in the beauty that the vehicle has to offer</span>
            </div>

           </div>
        </div>

         <div class="col" style="width: 18rem;">

          <div class="box-part text-center">

                        <i class="fa-solid fa-money-bill-trend-up fa-3x" aria-hidden="true"></i>

            <div class="title">
            <br>
            <br>
              <h4>List your vehicle</h4>
            </div>

            <div class="text">
              <span>Have a vehicle that you don't use? Feel free to list it!</span>
            </div>

           </div>
        </div>


        </div>
                </div>
    </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://media1.thehungryjpeg.com/thumbs2/ori_3657528_t0aph6glz2smm2osvo309xlt6qm0wejw615yl6xt_monogram-hw-logo-design.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# <%= link_to "My Listings", "#", class: "dropdown-item" %>
              <%= link_to "My Listings", mylistings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/vehicles/_info_window.html.erb
<h2><%= vehicle.name %></h2>
<p><%= vehicle.address %></p>
<p><%= vehicle.price %></p>

app/views/vehicles/index.html.erb
<%# <section class="Card">
  <div class="container">
    <h2 class="card-heading">All Vehicles</h2>
    <div class="row">
      <% @vehicles.each do |vehicle| %>
        <%# <div class="col-sm-6 col-md-4">
          <%= render 'shared/card', vehicle: vehicle %>
        <%# </div>
      <% end %>
    <%# </div>
  </div>
</section> %>
<%# <div> %>
  <section id="header" class="jumbotron text-center">
  <%= form_with url: vehicles_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a vehicle"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  <br>
      <h1 class="display-3">Luxury Vehicles</h1>
      <p class="lead">Discover luxury vehicles below and hire the car / boat of your dreams.</p>
  </section>
<%# </div> %>

<%# <div class ="split left"> %>
  <section id="gallery">
  <br>
  <h2> Current Listings: </h2>
    <div class="container">
      <div class="row" style="width: 100%;">
          <% @vehicles.each do |vehicle| %>
          <%# <% if vehicle.category == "Yacht" then%>
             <div class="col">
            <%= link_to  vehicle_path(vehicle) do %>
                <div class="card" style="width: 20rem;">
                   <%# <img class="card-img-top img-fluid" src="" alt="" class="mx-auto d-block"> %>
                     <%=cl_image_tag vehicle.image.key, class: "mx-auto d-block card-img-top img-fluid" %>
                  <div class="card-body">
                    <h5 class="card-title" style="color:#094067"><%= vehicle.name%></h5>
                    <p class="card-price" style="color:#5f6c7b;">Price: £<%= vehicle.price%> p/hr</p>
                  </div>
                </div>
            <%# <% end %>
            <% end %>
            </div>
          <% end %>
        </div>
    </div>
  </section>
<%# </div> %>
<%# <div class ="split right"> %>
<div class="map">
        <div style="width: 100%; height:1200px;"
          data-controller="map"
           data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
</div>
<%# </div> %>
<%# <%= cl_image_tag("sxheg955syqgeeu5qflo",
      width: 400, height: 300, crop: :fill) %>

app/views/vehicles/mylistings.html.erb
<div class="container">
            <div class="text-center mt-5">
                <h1>My Listings</h1>
          </section>
            </div>
<div class="box-index" >
    <div class="container">
      <div class="row justify-content-center" >
          <% @vehicles.each do |vehicle| %>
          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12" style="width: 18rem;">
          <div class="box-part text-center">
          <%=cl_image_tag vehicle.image.key, class: "img-mx-auto d-block card-img-top img-fluid" %>
            <div class="title">
                        <br>
                        <br>
              <h4><%= vehicle.name%></h4>
            </div>
            <div class="text">
              <span><%= vehicle.address%></span>
            </div>
          <%=  link_to "View", vehicle_path(vehicle), class: "btn btn-cancel"%>
           </div>
        </div>
            <% end %>

app/views/vehicles/new.html.erb
        <link href="css/styles.css" rel="stylesheet" />
<!--
<div id="wrapper">
  <div class="row">
    <div class="text-left form-login">
      <h2 class="text-center"><strong>Add your vehicle </strong></h2>

      <br>
      <%= simple_form_for @vehicle do |f| %>
      <%= f.error_notification %>
      <%= f.input :name, label: "Make of your vehicle", placeholder: "BMW, Mercedes..." %>
      <%= f.input :category, label: "Enter vehicle category", placeholder: "Aircraft, car, limousine, yacht" %>

      <%= f.input :price, label: "Enter the price per hour", placeholder: "£250, £1000, £400" %>
      <%= f.input :image, label: "Enter image URL", placeholder: "Google-image-url" %>
      <%= f.input :description, placeholder: "Courtesy of the 4-litre twin-turbo V8 engine, with 600 PS and 800 Nm of torque, you can accelerate from 0 to 62mph in just 3.6 seconds. Agile handling on the road is assured with dynamic all-wheel steering, and RS-air suspension, adjustable in three stages via Audi Drive Select." %>
      <%= f.input :address,
      input_html: {data: {address_autocomplete_target: "address"}},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
      %>
      <hr>
      <%= f.button :submit, "Submit", class: "btn btn-danger btn-lg"%>

      <% end %>
    </div>
  </div>

</div>
</div>
-->

<%= content_for(:after_js) do %>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyC8nUa2rua2jKRMY-bKdEW9GxRRh55wtIg"></script>
<% end %>

</div>

<div class="login-form">
  <div class="container">
    <div class="login-form">
      <div class="main-div">
        <div class="panel">

          <h2 style="color: #ff6969; font-size: 25px;"><strong>Add your vehicle</strong></h2>

        </div>

       <%= simple_form_for @vehicle do |f| %>

        <div class="row" style="margin-top: 2%;">

          <div class="col-sm-12 col-md-6 form-group">
          <%= f.input :name, placeholder: "BMW, Mercedes..." %>

          </div>

        <div class="row" style="margin-top: 2%;">


          <div class="col-sm-12 col-md-6 form-group">
            <%= f.input :category, label: "Enter vehicle category", collection: ["Aircraft", "Yacht", "Limousine", "Car"] %>
          </div>

        </div>

        <div class="row" style="margin-top: 2%;">

          <%# <div class="col-md-4 form-group">
            <label for="category">Vehicle category, please select</label>
            <select class="form-control" id="category" name="category">
              <option>Aircraft</option>
              <option>Car</option>
              <option>Limousine</option>
              <option>Yacht</option>
            </select>
          </div> %>
<%#
          <div class="row" style="margin-top: 2%;"> %>

          <div class="col-md-4 form-group">

         <%= f.input :price, label: "Enter the price per hour", placeholder: "£250, £1000, £400" %>
          </div>

      <div class="row" style="margin-top: 2%;">

          <div class="col-md-4 form-group">
         <%= f.input :address, label: "Enter your address", placeholder: "Mayfair, Soho..." %>
          </div>


      <div class="row" style="margin-top: 2%;">
          <div class="col-md-4 form-group">
          <%= f.input :description, placeholder: "Courtesy of the 4-litre twin-turbo V8 engine, with 600 PS and 800 Nm of torque, you can accelerate from 0 to 62mph in just 3.6 seconds. Agile handling on the road is assured with dynamic all-wheel steering, and RS-air suspension, adjustable in three stages via Audi Drive Select." %>
          </div>
          <%# IMAGES FOLDER %>
            <%= f.input :image, as: :file %>
          <div class="row" style="margin-top: 2%;">



          <button type="submit" class="btn btn-primary">Create listing</button>

          <%end%>
        </div>

      </div>
    </div>
  </div>

app/views/vehicles/show.html.erb
        <!-- Product section-->
        <section class="">
            <div class="">
                <div class="d-flex  mx-4 mt-4">
                    <div class="">
                      <%= cl_image_tag @vehicle.image.key, height: 300, width: 400, crop: :fill, style: 'object-fit: fit'%>
                    </div>
                    <div class="p-4">
                        <div class="small mb-1"></div>
                        <h1 class=""><%= @vehicle.name %></h1>
                           <div class="row" style="margin-top: 2%;">
                        <div class="">
                            <span class="text-decoration-line-through"></span>
                            <span>$<%=@vehicle.price%>/per hour</span>
                        </div>
                           <div class="row" style="margin-top: 5%;">
                        <p class="lead"><%=@vehicle.description%></p>
                        <div class="d-flex">

                           <div class="row" style="margin-top: 5%;">

                            <%= simple_form_for [@vehicle, @booking] do |f| %>
                         <strong><%= f.input :hours, label: "Enter number of hours you would like to hire"%></strong>
                         <strong><%= f.input :date, as: :date, label: "Enter the date"%></strong>
                              <div class="row" style="width:400px;font-size:13pt;padding:2px; border:3px solid green">
                              <%= f.button :submit, "Submit", class: "btn btn-green btn-lg"%>
                            <% end %>
                        </div>
                        <%# <div style="width: 100%; height: 600px;"
                        data-controller="map"
                          data-map-markers-value="<%= @markers.to_json %>
                          <%# data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>

                    </div>
                </div>
            </div>
        </section>